version: 2

sphinx:
   configuration: docs/source/conf.py

formats:
   - pdf

python:
  version: "3.6"
  install:
    - method: pip
      path: .
      extra_requirements:
        - numpy, Cython
    - method: setuptools
      path: .
